name: locales-launch
base: core18
version: git
summary: A stage snap that fixes Glibc locales support
description: |
  This stage snap ships the `locales-launch` launcher and its dependencies to your snap, by incorporate this stage snap you can fix the Glibc locales support and allow applications that depend on it to work.

  Refer the following snapcraft forum topic for more information regarding using this remote part:
  
    _topic_title_
    _topic_url_

grade: stable
confinement: strict

parts:
  locales-launch:
    plugin: dump
    source: snap/local/launchers
    stage-packages:
    # For localedef(1)
    - libc-bin

    # For locale data used by localedef(1)
    - locales

    # All pre-generated locale data
    # DISABLED: Lots of duplicate data will be included in snap when this is staged, unless the target machine has no resource to generate them in runtime otherwise not using it
    #
    #   Lack of compiled locales breaks gettext based localisation - snapcraft - snapcraft.io
    #   https://forum.snapcraft.io/t/lack-of-compiled-locales-breaks-gettext-based-localisation/3758
    #
    #- locales-all

    organize:
      '*-launch': bin/
