name: locales-launch
base: core18
version: git
summary: A stage snap that fixes Glibc locales support
description: |
  This stage snap ships the `locales-launch` launcher and its dependencies to your snap, by incorporate this stage snap you can fix the Glibc locales support and allow applications that depend on it to work.

  Refer the following snapcraft forum topic for more information regarding using this remote part:
  
    _topic_title_
    _topic_url_

grade: stable
confinement: strict

# We only ship launcher here, don't do duplicate work
architectures:
- build-on: s390x
  run-on: all

parts:
  locales-launch:
    plugin: dump
    source: snap/local/launchers
    organize:
      '*-launch': bin/
